### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by jfranciscos4** [vrcca/flyway-vagrant-puppet-postgres-example#1]
Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'sfpc-centos'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Installing Puppet modules in "." with Librarian-Puppet...
[default] Destroying VM and associated drives...
[default] Running cleanup tasks for 'puppet' provisioner...
/home/jfsi/.vagrant.d/gems/gems/librarian-puppet-2.0.1/lib/librarian/puppet/source/forge/repo.rb:129:in `rescue in cache_version_unpacked!': Error executing puppet module install. Check that this command succeeds: (Librarian::Error)
puppet module install --version 4.6.0 --target-dir /home/jfsi/workspacePHP/projects/emprel/portal-compras/produtos/infraestrutura/sfpc-banco/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/puppetlabs-stdlib/4.6.0 --module_repository https://forge.puppetlabs.com --modulepath /home/jfsi/workspacePHP/projects/emprel/portal-compras/produtos/infraestrutura/sfpc-banco/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/puppetlabs-stdlib/4.6.0 --module_working_dir /home/jfsi/workspacePHP/projects/emprel/portal-compras/produtos/infraestrutura/sfpc-banco/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/puppetlabs-stdlib/4.6.0 --ignore-dependencies puppetlabs-stdlib
Error:
Error: Non-HTTP proxy URI: https://172.27.240.20:3128/
Error: Try 'puppet help module install' for usage
	from /home/jfsi/.vagrant.d/gems/gems/librarian-puppet-2.0.1/lib/librarian/puppet/source/forge/repo.rb:114:in `cache_version_unpacked!'
	from /home/jfsi/.vagrant.d/gems/gems/librarian-puppet-2.0.1/lib/librarian/puppet/source/forge/repo.rb:56:in `install_version!'
	from /home/jfsi/.vagrant.d/gems/gems/librarian-puppet-2.0.1/lib/librarian/puppet/source/forge.rb:114:in `install!'
	from /home/jfsi/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/manifest.rb:101:in `install!'
	from /home/jfsi/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/action/install.rb:49:in `block in install_manifests'
	from /home/jfsi/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `each'
	from /home/jfsi/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `install_manifests'
	from /home/jfsi/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/action/install.rb:39:in `perform_installation'
	from /home/jfsi/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/action/install.rb:12:in `run'
	from /home/jfsi/.vagrant.d/gems/gems/vagrant-librarian-puppet-0.9.0/lib/vagrant-librarian-puppet/action/librarian_puppet.rb:64:in `provision'
	from /home/jfsi/.vagrant.d/gems/gems/vagrant-librarian-puppet-0.9.0/lib/vagrant-librarian-puppet/action/librarian_puppet.rb:29:in `block in call'
	from /home/jfsi/.vagrant.d/gems/gems/vagrant-librarian-puppet-0.9.0/lib/vagrant-librarian-puppet/action/librarian_puppet.rb:28:in `each'
	from /home/jfsi/.vagrant.d/gems/gems/vagrant-librarian-puppet-0.9.0/lib/vagrant-librarian-puppet/action/librarian_puppet.rb:28:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:13:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/set_name.rb:48:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `run'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/call.rb:51:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `run'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/call.rb:51:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `run'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/call.rb:51:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/call.rb:57:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/call.rb:57:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `run'
	from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:147:in `action'
	from /usr/lib/ruby/vendor_ruby/vagrant/batch_action.rb:63:in `block (2 levels) in run'

**Comment by jfranciscos4** [comment]
resolvido
